= Emergency: I’m being tempted and I want to give in to the sin

If you are a believer and are being seduced by an irresistible temptation right now, you must immediately pray to the Lord for help, because without Him you will be unable to stand against it.

> Lord Jesus, I need your help. I am being tempted beyond what I can bear. Please fill me with your Holy Spirit so I might know and believe that the joy of walking with you is far better than this temporary pleasure. Deliver me and protect me from my flesh and any demonic powers. I beg you to put out this fire of lust that has been kindled in my heart and mind. I am dependent on you for help; give me power through the Spirit to reject the lies I’m being told and to cling to your truths instead. In Jesus’ name, Amen.

Continue constantly in prayer, but you must also act immediately and with all of your strength to resist this temptation. If you have asked God for help with a sincere heart, you must also have faith that He will supply the strength you need, for “the Lord knows how to rescue the godly from trials.” (2 Peter 2:9) Earnestly fight the temptation by doing the following:

== Physically remove yourself from the situation

If you are in a situation where you are being tempted because of your surroundings, leave immediately. Escape the environment that may be contributing to the temptation so that you can see your situation with clear eyes. If you can’t remove yourself, close your eyes and attempt to mentally remove any distraction from the difficult labor ahead.

* “God is faithful, and he will not let you be tempted beyond your ability, but with the temptation he will also _provide the way of escape_, that you may be able to endure it.” *(1 Cor. 10:13)*
* “_Flee youthful passions_ and pursue righteousness, faith, love, and peace, along with those who call on the Lord from a pure heart.” *(2 Tim. 2:22)*
* “She caught [Joseph] by his garment, saying, ‘Lie with me.’ But he left his garment in her hand and _fled and got out of the house._” *(Gen. 39:12)*

== Address the lies with God’s truth and promises

Temptation steals your attention from what is true and replaces it with lies. These lies, if unchecked, result in an overwhelming feeling of hopelessness and despair. Your mind is likely darkened and unable to make a right judgment of things at this moment. You must instead fixate on the promises and faithfulness of God, which will drown out the lies. Ultimately you must reinvigorate your heart and mind with a vision of the supremacy of Christ, who is a vastly superior satisfaction than the sin attempting to take His place.
