= Highlights from Mortification of Sin

== Chapter 1

[quote, Page 47]
____
The choicest believers, who are assuredly freed from the condemning power of sin, ought yet to make it their business all their days to mortify the indwelling power of sin.
____

== Chapter 2

[quote, Page 54]
____
The contest is for our lives and souls. Not to be daily employing the Spirit and new nature for the mortifying of sin is to neglect that excellent succor that God has given us against our greatest enemy. If we neglect to make use of what we have received, God may justly hold his hand from giving us more. His graces, as well as his gifts, are bestowed on us to use, exercise, and trade with. Not to be daily mortifying sin is to sin against the goodness, kindness, wisdom, grace, and love of God, who has furnished us with a principle of doing it.
____

[quote, Page 54]
____
This is that which I intend: by the omission of this duty, grace withers, lust flourishes, and the frame of the heart grows worse and worse; and the Lord knows what desperate and fearful issues it has had with many.
____

[quote, Page 54]
____
And when poor creatures will take blow after blow, wound after wound, foil after foil, and never rouse up themselves to a vigorous opposition, can they expect anything but to be hardened through the deceitfulness of sin, and that their souls should bleed to death (2 John 8)?
____

[quote, Page 55]
____
It is our duty to be "perfecting holiness in the fear of God" (2 Cor. 7:1); to be "growing in grace" every day (1 Pet. 2:2; 2 Pet. 3:18); to be "renewing our inward man day by day" (2 Cor. 4:16). Now, this cannot be done without the daily mortifying of sin. Sin sets its strength against every act of holiness and against every degree we grow to. Let not that man think he makes any progress in holiness who walks not over the bellies of his lusts. He who does not kill sin in his way takes no steps toward his journey's end. He who finds not opposition from it, and who sets not himself in every particular to its mortification, is at peace with it, not dying to it.
____

[quote, 56]
____
When a man has confirmed his imagination to such an apprehension of grace and mercy as to be able, without bitterness, to swallow and digest daily sins, that man is at the very brink of turning the grace of God into lasciviousness and being hardened by the deceitfulness of sin.
____

[quote, 57]
____
They deny prodigality, but with worldliness; they separate from the world, but live wholly to themselves, taking no care to exercise lovingkindness in the earth; or they talk spiritually, and live vainly; mention communion with God, and are every way conformed to the world; boasting of forgiveness of sin, and never forgiving others. And with such considerations do poor creatures harden their hearts in their unregeneracy.
____

== Chapter 3

[quote, 57]
____
He only is sufficient for this work; all ways and means without him are as a thing of naught; and he is the great efficient of it -- he works in us as he pleases.
____

[quote, 59]
____
In a word, they have sundry means to mortify the natural man, as to the natural life here we lead; none to mortify lust or corruption.
____

[quote, 60]
____
Men are galled with the guilt of a sin that has prevailed over them; they instantly promise to themselves and God that they will do so no more; they watch over themselves and pray for a season until this heat waxes cold and the sense of sin is worn off -- and so mortification goes also, and sin returns to its former dominion.
____

[quote, 60]
____
He is promised of God to be given unto us to do this work. The taking away of the stony heart -- that is, the stubborn, proud, rebellious, unbelieving heart -- is in general the work of mortification that we treat of. Now this is still promised to be done by the Spirit, "I will give my Spirit, and take away the stony heart" (Ezekiel 11:19; 36:26), and by the Spirit of God is this work wrought when all means fail (Isaiah 57:17-18). We have all our mortification from the gift of Christ, and all the gifts of Christ are communicated to us and given us by the Spirit of Christ: "Without Christ we can do nothing" (John 15:5). All communications of supplies and relief, in the beginnings, increasings, actings of the grace whatsoever, from him, are by the Spirit, by whom he alone works in and upon believers.
____

[quote, 61]
____
He is the fire which burns up the very root of lust.
____

[quote, 62]
____
It is no otherwise the work of the Spirit but as all graces and good works which are in us are his. He "works in us to will and to do of his own good pleasure" (Phil. 2:13); he works "all our works in us" (Isa. 26:12) -- "the work of faith with power" (2 Thess. 1:11; Col. 2:12); he causes us to pray, and is a "spirit of supplication".
____

[quote, 62]
____
The Holy Ghost works in us and upon us, we are fit to be wrought in and upon; that is, so as to preserve our own liberty and free obedience.
____

[quote, 62]
____
And, indeed, I might here bewail the endless, foolish labor of poor souls, who, being convinced of sin and not able to stand against the power of their convictions, do set themselves, by innumerable perplexing ways and duties, to keep down sin, but, being strangers to the Spirit of God, all in vain. They combat without victory, have war without peace, and are in slavery all of their days.
____

== Chapter 4

[quote, 65]
____
As sin weakens, so it darkens the soul. It is a cloud, a thick cloud, that spreds itself over the face of the soul, and intercepts all the beams of God's love and favor. It takes away all
____

[quote, 65]
____
Men that are sick and wounded under the power of lust make many applications for help; they cry to God when the perplexity of their thoughts overwhelms them, even to God do they cry, but are not delivered; in vain do they use many remedies -- "they shall not be healed." So, "Ephraim saw his sickness, and Judah saw his wound" (Hos. 5:13), and attempted sundry remedies: nothing will do until they come to "acknowledge their offense" (v. 15). Men may see their sickness and wounds, but yet, if they make not due applications, their cure will not be effected.
____

[quote, 66]
____
The heart is like the sluggard's field -- so overgrown with weeds that you can scarce see the good corn. Such a man may search for faith, love, and zeal, and scarce be able to find any; and if he does discover that these graces are there yet alive and sincere, yet they are so weak, so clogged with lusts, that they are of very little use; they remain, indeed, but are ready to die. But now let the heart be cleansed by mortification, the weeds of lust constantly and daily rooted up (as they spring daily, nature being their proper soil), let room be made for grace to thrive and flourish -- how will every grace act its part, and be ready for every use and purpose!
____

== Chapter 5

[quote, 69]
____
Suppose a man to be a true believer, and yet finds in himself a powerful and indwelling sin, leading him captive to the law of it, consuming his heart with trouble, perplexing his thoughts, weakening his soul as to duties of communion with God, disquieting him as to peace, and perhaps defiling his conscience, and exposing him to hardening through the deceitfulness of sin, what shall he do? What course shall he take and insist on for the mortification of this sin, lust, distemper, or corruption, to such a degree as that, though it be not utterly destroyed, yet, in his contest with it, he may be enabled to keep up power, strength, and peace in communion with God?
____

[quote, 69]
____
Now, though doubtless there may be, by the Spirit and grace of Christ, a wonderful success and eminency of victory against any sin be attained, so that a man may have almost constant triumph over it, yet an utter killing and destruction of it, that it should not be, is not in this life to be expected.
____

[quote, 70]
____
When a man on some outward respects forsakes the practice of any sin, men perhaps may look on him as a changed man. God knows that to his former iniquity he has added cursed hypocrisy, and is now on the safer path to hell than he was before. He has got another heart than he had, that is more cunning; not a new heart, that is more holy.
____

[quote, 71]
____
A man may be sensible of a lust, set himself against the eruptions of it, take care that it shall not break forth as it has done, but in the meantime suffer the same corrupted habit to vent itself some other way; as he who heals and skins a running sore thinks himself cured, but in the meantime his flesh festers by the corruption of the same humor, and breaks out in another place.

And the same is in the case of bartering of lusts, and leaving to serve one that a man may serve another. He that changes pride for worldliness, sensuality for Pharasaism, vanity in himself to the contempt of others, let him not think that he has mortified the sin that he seems to have left. He has changed his master, but is a servant still.
____

[quote, 72]
____
When [sin] has had some sad eruption, to the disturbance of his peace, terror of his conscience, dread of scandal, and evident provocation of God ... [it] awakens and stirs up all that is in the man, and amazes him, fills him with abhorrency of sin and himself for it; sends him to God, makes him cry out as for life, to abhor his lust as hell and to set himself against it. The whole man, spiritual and natural, being now awakened, sin shrinks in its head, appears not, but lies as dead before him... and lust is quiet for a season, being run down before [him]... Accordingly, sin is quiet, stirs not, seems to be mortified; not, indeed, that it has received any one wound, but merely because the soul has possessed its faculties, whereby it should exert itself, with thoughts inconsistent with the motions thereof; which, when they are laid aside, sin returns again to its former life and vigor... When the hurry is over and the inquest past, the thief appears again alive, and is as busy as ever at his work.
____

== Chapter 6

[quote, 73]
____
And the reason why a natural man is not always perpetually in the pursuit of some one lust, night and day, is because he has many to serve, every one crying to be satisfied; thence he is carried on with great variety, but still in general he lies toward the satisfaction of self.
____

[quote, 73]
____
And a sinful, depraved habit, as in really other things, so in this, differs from all natural or moral habits whatsoever: for whereas they incline the soul gently and suitably to itself, sinful habits impel with violence and impetuousness; whence lusts are said to fight or wage "war against the soul" (1 Pet. 2:11) -- to rebel or rise up in war with that conduct and opposition which is usual therein (Rom. 7:23) -- to lead captive, or effectually captivating upon success in battle -- all works of great violence and impetuousness.
____

[quote, 74]
____
Now, the first thing in mortification is the weakening of this habit of sin or lust, that it shall not, with that violence, earnestness, frequency, rise up, conceive, tumultuate, provoke, entice, disquiet, as naturally it is apt to do (James 1:14-15). I shall desire to give one caution or rule by the way, and it is this: Though every lust does in its own nature equally, universally, incline and impel to sin, yet this must be granted with these two limitations: One lust, or a lust in one man, may receive many accidental improvements, heightenings, strengthenings, which may give it life, power, and vigor, exceedingly above what another lust has, or the same lust (that is, of the same kind and nature) in another man.

But especially, lust gets strength by temptation. When a suitable temptation falls in with a lust, it gives it a new life, vigor, power, violence, and rage, which it seemed not before to have or to be capable of.
____

[quote, 75]
____
I say, then, that the first thing in mortification is the weakening of this habit, that it shall not impel and tumultuate as formerly; that it shall not entice and draw aside; that it shall not disquiet and perplex the killing of its life, vigor, promptness, and readiness to be stirring.
____
