These are notes from various readings and scriptures about how to have meaningful and satisfying quiet times with God. I initially started these notes on June 16, 2017 because I have been feeling distant from God and have not been practicing the discipline of quiet times with Him.


== Source Notes

=== Westminster Larger Catechism

The following list contains highlights from the Westminster Larger Catechism that I think are particularly important to understanding the means of grace, or spiritual disciplines.

[quote, Q.1]
____
Man's chief and highest end is to glorify God, and fully to enjoy him forever.
____

The implication of Q1 is that disciplines should be exercised to facilitate glorifying and enjoying God. If the true meaning of life is to glorify and enjoy God, and enjoyment is found by knowing God's actions and character, then every effort should be made to practice spiritual disciplines as a means to that end.

[quote, Q.75]
____
Sanctification is a work of God's grace, whereby they whom God hath, before the foundation of the world, chosen to be holy, are in time, through the powerful operation of his Spirit applying the death and resurrection of Christ unto them, renewed in their whole man after the image of God; having the seeds of repentance unto life, and all other saving graces, put into their hearts, and those graces so stirred up, increased, and strengthened, as that they more and more die unto sin, and rise unto newness of life.
____

For the purpose of spiritual disciplines, it seems reasonable to condense these sentences to: "Sanctification is a work of God's grace...through the powerful operation of his Spirit...[whereby His] graces are stirred up, increased, and strengthened." Spiritual disciplines, then, have no effect without the help and power of God to affect me. With God's help, I should endeavor to stir up, increase, and strengthen my faith and trust in Him.

[quote, Q.91]
____
The duty which God requireth of man, is obedience to his revealed will.
____

Practicing spiritual disciplines should be an exercise of obedience.

[quote, Q.154]
____
The outward and ordinary means whereby Christ communicates to his church the benefits of his mediation, are all his ordinances; especially the word, sacraments, and prayer; all which are made effectual to the elect for their salvation.
____

Note the phrase "are made effectual"; The means are not inherently effective, but are made effective by God.

[quote, Q.155]
____
The Spirit of God maketh the reading, but especially the preaching of the word, an effectual means of enlightening, convincing, and humbling sinners; of driving them out of themselves, and drawing them unto Christ; of conforming them to his image, and subduing them to his will; of strengthening them against temptations and corruptions; of building them up in grace, and establishing their hearts in holiness and comfort through faith unto salvation.
____

Once again, reading the Bible is _made_ effective through the Holy Spirit. When made effective, it:

* Enlightens
* Convinces
* Humbles
* Draws us to Christ
* Conforms us to Him
* Subdues our will
* Strengthens us from temptations
* Builds us up

[quote, Q.157]
____
The holy Scriptures are to be read with an high and reverent esteem of them; with a firm persuasion that they are the very Word of God, and that he only can enable us to understand them; with desire to know, believe, and obey the will of God revealed in them; with diligence, and attention to the matter and scope of them; with meditation, application, self-denial, and prayer.
____


[quote, Q.182]
____
We not knowing what to pray for as we ought, the Spirit helpeth our infirmities, by enabling us to understand both for whom, and what, and how prayer is to be made; and by working and quickening in our hearts (although not in all persons, nor at all times, in the same measure) those apprehensions, affections, and graces which are requisite for the right performance of that duty.
____

=== How to Have Intimacy With God -- desiringgod.org

**Source**: http://www.desiringgod.org/articles/how-to-have-intimacy-with-god

* Intimate fellowship with God is the goal.
* Intimacy can be defined as a relational closeness and a deepness, where the key ingredient is _trust_.
* Our perception of God's nearness or distance comes down to our trust in Him.
* Disruptions in our trust are the consequence of sin and disappointment.
* Intimacy and knowledge aren't the same thing. Knowledge is not synonymous with trust.
* Subjective, aesthetic experiences foster an environment for greater intimacy, but do not inherently build it.
* We draw near to God through faith in Christ and by putting our trust in his great promises.
* "God is impressed with our faith, not our feats. Where faith is lacking, he is not pleased with the quantity of our knowledge or the quality of our aesthetic experiences."
* God _wants_ intimacy with you, and he wants you to trust Him.


[quote, Psalm 73:28 (ESV)]
____
But for me it is good to be near God;

I have made the Lord God my refuge,

that I may tell of all your works.
____


[quote, James 4:8 (ESV)]
____
Draw near to God, and he will draw near to you. Cleanse your hands, you sinners, and purify your hearts, you double-minded.
____


[quote, John 5:39-40 (ESV)]
____
You search the Scriptures because you think that in them you have eternal life; and it is they that bear witness about me, yet you refuse to come to me that you may have life.
____


[quote, Hebrews 4:16 (ESV)]
____
Let us then with confidence draw near to the throne of grace, that we may receive mercy and find grace to help in time of need.
____


[quote, Hebrews 11:6 (ESV)]
____
And without faith it is impossible to please him, for whoever would draw near to God must believe that he exists and that he rewards those who seek him.
____


[quote, Proverbs 3:5 (ESV)]
____
Trust in the Lord with all your heart, and do not lean on your own understanding.
____

=== Quiet Time Doesn't Earn God's Grace -- desiringgod.org

**Source**: http://www.desiringgod.org/articles/quiet-time-doesn-t-earn-god-s-grace

* The "means of grace" are not "means _to_ grace".
* Spiritual disciplines, such as prayer or Bible study, cannot "manufacture grace."
* You cannot barter with God via spiritual disciplines, because past sins, present sins, and future sins are already paid for. Anything that happens now is for God's glory and my good.
* When we participate in the means of grace, we are feasting upon the grace that's already present.
* The means of grace are a way of understanding His ways, His words, and His heart, and our love for Him grows as a result.
