These are notes from various readings and scriptures about how to have meaningful and satisfying quiet times with God. I initially started these notes on June 16, 2017 because I have been feeling distant from God and have not been practicing the discipline of quiet times with Him.

== References and Notes

=== How to Have Intimacy With God -- desiringgod.org

**Source**: http://www.desiringgod.org/articles/how-to-have-intimacy-with-god

* Intimate fellowship with God is the goal.
* Intimacy can be defined as a relational closeness and a deepness, where the key ingredient is _trust_.
* Our perception of God's nearness or distance comes down to our trust in Him.
* Disruptions in our trust are the consequence of sin and disappointment.
* Intimacy and knowledge aren't the same thing. Knowledge is not synonymous with trust.
* Subjective, aesthetic experiences foster an environment for greater intimacy, but do not inherently build trust.
* We draw near to God through faith in Christ and by putting our trust in his great promises.
* "God is impressed with our faith, not our feats. Where faith is lacking, he is not pleased with the quantity of our knowledge or the quality of our aesthetic experiences."
* **Important:** God _wants_ intimacy with you, and he wants you to trust Him.


[quote, Psalm 73:28 (ESV)]
____
But for me it is good to be near God;

I have made the Lord God my refuge,

that I may tell of all your works.
____

[quote, James 4:8 (ESV)]
____
Draw near to God, and he will draw near to you. Cleanse your hands, you sinners, and purify your hearts, you double-minded.
____

[quote, John 5:39-40 (ESV)]
____
You search the Scriptures because you think that in them you have eternal life; and it is they that bear witness about me, yet you refuse to come to me that you may have life.
____

[quote, Hebrews 4:16 (ESV)]
____
Let us then with confidence draw near to the throne of grace, that we may receive mercy and find grace to help in time of need.
____

[quote, Hebrews 11:6 (ESV)]
____
And without faith it is impossible to please him, for whoever would draw near to God must believe that he exists and that he rewards those who seek him.
____

[quote, Proverbs 3:5 (ESV)]
____
Trust in the Lord with all your heart, and do not lean on your own understanding.
____

=== Quiet Time Doesn't Earn God's Grace -- desiringgod.org

**Source**: http://www.desiringgod.org/articles/quiet-time-doesn-t-earn-god-s-grace

* The "means of grace" are not "means _to_ grace".
* Spiritual disciplines, such as prayer, Bible reading, fellowship, scripture reading, are not "manufacturing grace" -- somehow as a means to barter with God.
* Past sins, present sins, and future sins are already paid for. Anything that happens now is for God's glory and my good.
* When we participate in the means of grace, we are feasting upon the grace that's already present.
* The means of grace are a way of understanding His ways, His words, and His heart, and our love for Him grows as a result.
